# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  body_converter:
    enabled: true
    validate: true

  param_fetcher_listener:  true

  view:
    formats: { json: true, xml: false, rss: false }
    view_response_listener: true

  exception:
    enabled: false
    #exception_controller: 'fos_rest.exception.controller:showAction'

  serializer:
    serialize_null: true

  format_listener:
    rules:
      - { path: '^/', priorities: ['json'], fallback_format: 'json' }